language: php

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - composer install --dev --no-interaction

before_script:
  - composer require php-coveralls/php-coveralls:^2.1.0
  - composer install -n

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml

after_success:
  - vendor/bin/php-coveralls --coverage_clover=clover.xml

notifications:
    email: true
